# Generated by Django 5.1.2 on 2025-10-07 20:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenAnalizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='uploads/', verbose_name='Imagen Original')),
                ('imagen_procesada', models.ImageField(blank=True, null=True, upload_to='processed/', verbose_name='Imagen Procesada')),
                ('madurez', models.CharField(blank=True, max_length=20, verbose_name='Estado de Madurez')),
                ('conf_mad', models.FloatField(default=0.0, verbose_name='Confianza Madurez')),
                ('num_detecciones', models.IntegerField(default=0, verbose_name='Número de Detecciones')),
                ('enfermedad', models.CharField(blank=True, max_length=100, verbose_name='Enfermedad Detectada')),
                ('conf_enf', models.FloatField(default=0.0, verbose_name='Confianza Enfermedad')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción de la Enfermedad')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Análisis')),
                ('procesado', models.BooleanField(default=False, verbose_name='Procesado')),
            ],
            options={
                'verbose_name': 'Imagen Analizada',
                'verbose_name_plural': 'Imágenes Analizadas',
                'ordering': ['-fecha'],
            },
        ),
    ]
